// app/career/page.tsx
import MaxWidth from '../maxWidth';

export default function CareerPage() {
  return (
    <MaxWidth>
      <h1>経歴</h1>
      <div id="sc_com_container">
        <div className="box_container">
          <h2 className="title">2017/04 一関工業高等専門学校 入学 (未来創造工学科改組後一期生)</h2>
          <div className="box"><div className="vertical_line" /><div className="content"><p>１年次: 教員の名言を管理するアプリ CppMeigens を作った。謎にC++で作られている。なお、当時はデータベースを知らなかったため、JSON パーサライブラリ picojson を使って名言を管理する方式を取っていた。ソースはHDDの闇の中に。残念。</p></div></div>
          <h3 className="title">( 2018/04 情報・ソフトウェア系 配属 )</h3>
          <div className="box"><div className="vertical_line" /><div className="content">
            <p>2年次(情報・ソフトウェア系 配属): 授業にて、企業などで提供されている何かしらの API を選んでそれを叩くアプリを Python で作ろうと言われた。なので、自分で API から作ることにした。ちょうど昨年 CppMeigens を作っていたので、自宅サーバ上で Flask を使って API 化し、これを叩くアプリを作り、CppMeigens をサーバクライアントシステムに改良した。なお、この後友人がデータベースを用いて再設計し、Discord API を用いてより素晴らしい名言管理サービスを作ってくれたので、すぐに役目を終えた。</p>
            <p>3年次: 基本情報から取って次に企業である程度経験を積んで応用情報、というレールの上を走るのはなんか癪なので、はじめに応用情報を取った。当時17歳。令和元年度秋試験のことである。また、Web アプリを作ろうというグループワークがあった。Markdown 記事をメンバに書いてもらって、それを一覧表示するアプリを私が作るということになった。当時 SPA の概念や React, Angular, Vue などのフレームワークは知らなかったが、「どうやら DOM というので html の構造ができていて、それは JS で操作できるらしい。じゃあページ遷移を JS でやりたかったら DOM 操作で切り替えるのが普通か～。」というのをやった。自前で SPA を実装していたことになる。</p>
            <p>4年次: 画像処理の授業でPNM形式の画像に対して微分フィルタはじめ色々なものを実装したりしていた。うつ状態になりはじめる。</p>
            <p>5年次: 席次2位(35人中)で卒業した。なおこの時期のできる高専生は編入や研究で皆忙しくて成績に力を注げない。というのでこの数字にさしたる意味はない。ただ事実なので書いておいた。この年に CG の授業で東京タワーを作った。また、blenderから出力したオブジェクトファイルをオブジェクトごとに分割するプログラム、及び OpenGL で読み込んでくるくる回すコードを書いた。ゲームなどを作る上で基礎的に重要なものを実装したと思う。</p>
          </div></div>
          <h2 className="title">2022/03 一関工業高等専門学校 卒業</h2>
        </div>

        <div className="box_container">
          <h2 className="title">2022/04 新潟大学理学部理学科数学プログラム 入学 (世間一般で云う理学部数学科)</h2>
          <div className="box"><div className="vertical_line" /><div className="content">
            <p>3年次: 物質反応化学の試験で私だけ満点だったことはイキろう。関数解析学のバケモンみたいな院生に出会う。うつ状態になり、何もできない。試験前日に焦りはじめ、鬼のように資料を眺めまくり、大量の証明を暗記し、複素解析学の試験に合格する。ただし代償としてうつ状態が急性期に陥り、大学のリフレッシュルームで眠りながら叫び(迷惑)、複素解析学の知識を失い、寝込み続ける。ADHD/ASDと診断される。</p>
            <p>4年次: 音声処理関連で興味があったため、ゼミでフーリエ解析の本を読み始める。また、唐突にプログラムを書きたくなりはじめ、ポートフォリオを準備したり(これの以前に作った第一世代のもの)、マイクラの全自動バックアッププラグインを開発し始める。マイクラの自動バックアップに必要な小さなライブラリとして CronParser(crontabのようなもの)、DIrBackup(ファイル削除を考慮する差分・増分バックアップライブラリ)を作り上げる。</p>
          </div></div>
          <h2 className="title">2024/03 新潟大学理学部 卒業</h2>
        </div>

        <div className="box_container">
          <h2 className="title">2024/04 新潟大学大学院自然科学研究科数理物質科学専攻数理科学コース 入学</h2>
          <div className="box"><div className="vertical_line" /><div className="content">
            <p>1年次: まず予定を立てた。</p>
            <ul>
              <li>夏季休業中に就活(インターン・面接)を終え、第一志望の内定をもらう。</li>
              <li>M1の一学期中に修論とゼミ以外の修了に必要な単位全てを取得する。</li>
              <li>内定後バイトの予定を立てる。</li>
            </ul>
            <p>無事完遂。私の体力的に第一志望以外に複数社を受けることは難しかったので、せいぜいスカウトが来た企業(のうちただの宣伝ではなくちゃんと私のプロフィールを読んでいる企業)の面接を受けるくらいにして、インターンは第一志望だけ参加した。インターンで教わったことで印象的なのはテストの書き方。自分のコードが十分にモジュール化されていなくてテストに向いていないということが分かったので、Layered ArchitectureはじめinterfaceとDIによる抽象化に基づいたコードを学んで身につけるきっかけになった。</p>
          </div></div>
          <h2 className="title">今に至る</h2>
        </div>

        <div className="box_container">
          <h2 className="title_future">(予定) 2026/04 フラー株式会社 入社(サーバーサイドエンジニア)</h2>
        </div>
      </div>
    </MaxWidth>
  );
}

// src/routes/career/+page.svelte
<script lang="ts">
  import MaxWidth from "../../components/maxWidth.svelte";
</script>

<MaxWidth>
  <h1>経歴</h1>
  <div id="sc_com_container">
    <div class="box_container">
      <h2 class="title">2017/04 一関工業高等専門学校 入学 (未来創造工学科改組後一期生)</h2>
      <div class="box">
        <div class="vertical_line"></div>
        <div class="content">
          <p>１年次: {`
            教員の名言を管理するアプリ CppMeigens を作った。
            謎にC++で作られている。なお、当時はデータベースを知らなかったため、
            JSON パーサライブラリ picojson を使って名言を管理する方式を取っていた。
            ソースはHDDの闇の中に。残念。
          `}</p>
        </div>
      </div>
      <h3 class="title">( 2018/04 情報・ソフトウェア系 配属 )</h3>
      <div class="box">
        <div class="vertical_line"></div>
        <div class="content">
          <p>2年次(情報・ソフトウェア系 配属): {`
            授業にて、企業などで提供されている何かしらの API を選んでそれを叩くアプリを Python で作ろうと言われた。
            なので、自分で API から作ることにした。ちょうど昨年 CppMeigens を作っていたので、
            自宅サーバ上で Flask を使って API 化し、これを叩くアプリを作り、CppMeigens をサーバクライアントシステムに改良した。
            なお、この後友人がデータベースを用いて再設計し、
            Discord API を用いてより素晴らしい名言管理サービスを作ってくれたので、すぐに役目を終えた。
          `}</p>
          <p>3年次: {`
            基本情報から取って次に企業である程度経験を積んで応用情報、というレールの上を走るのはなんか癪なので、
            はじめに応用情報を取った。当時17歳。令和元年度秋試験のことである。
            また、Web アプリを作ろうというグループワークがあった。Markdown 記事をメンバに書いてもらって、
            それを一覧表示するアプリを私が作るということになった。当時 SPA の概念や React, Angular, Vue などのフレームワークは知らなかったが、
            「どうやら DOM というので html の構造ができていて、それは JS で操作できるらしい。じゃあページ遷移を JS でやりたかったら DOM 操作で切り替えるのが普通か～。」
            というのをやった。自前で SPA を実装していたことになる。
          `}</p>
          <p>4年次: 画像処理の授業でPNM形式の画像に対して微分フィルタはじめ色々なものを実装したりしていた。うつ状態になりはじめる。</p>
          <p>
            5年次: {`
            席次2位(35人中)で卒業した。なおこの時期のできる高専生は編入や研究で皆忙しくて成績に力を注げない。
            というのでこの数字にさしたる意味はない。ただ事実なので書いておいた。
            この年に CG の授業で東京タワーを作った。
            また、blenderから出力したオブジェクトファイルをオブジェクトごとに分割するプログラム、
            及び OpenGL で読み込んでくるくる回すコードを書いた。ゲームなどを作る上で基礎的に重要なものを実装したと思う。
          `}</p>
        </div>
      </div>
      <h2 class="title">2022/03 一関工業高等専門学校 卒業</h2>
    </div>
  
    <div class="box_container">
      <h2 class="title">2022/04 新潟大学理学部理学科数学プログラム 入学 (世間一般で云う理学部数学科)</h2>
      <div class="box">
        <div class="vertical_line"></div>
        <div class="content">
          <p>3年次: {`
            物質反応化学の試験で私だけ満点だったことはイキろう。
            関数解析学のバケモンみたいな院生に出会う。
            うつ状態になり、何もできない。試験前日に焦りはじめ、
            鬼のように資料を眺めまくり、大量の証明を暗記し、複素解析学の試験に合格する。
            ただし代償としてうつ状態が急性期に陥り、大学のリフレッシュルームで眠りながら叫び(迷惑)、
            複素解析学の知識を失い、寝込み続ける。ADHD/ASDと診断される。
          `}</p>
          <p>4年次: {`
            音声処理関連で興味があったため、ゼミでフーリエ解析の本を読み始める。また、唐突にプログラムを書きたくなりはじめ、
            ポートフォリオを準備したり(これの以前に作った第一世代のもの)、マイクラの全自動バックアッププラグインを開発し始める。
            マイクラの自動バックアップに必要な小さなライブラリとして 
            CronParser(crontabのようなもの)、DIrBackup(ファイル削除を考慮する差分・増分バックアップライブラリ)を作り上げる。
          `}</p>
        </div>
      </div>
      <h2 class="title">2024/03 新潟大学理学部 卒業</h2>
    </div>
  
    <div class="box_container">
      <h2 class="title">2024/04 新潟大学大学院自然科学研究科数理物質科学専攻数理科学コース 入学</h2>
      <div class="box">
        <div class="vertical_line"></div>
        <div class="content">
          <p>
            1年次: まず予定を立てた。
          </p>
          <ul>
            <li>夏季休業中に就活(インターン・面接)を終え、第一志望の内定をもらう。</li>
            <li>M1の一学期中に修論とゼミ以外の修了に必要な単位全てを取得する。</li>
            <li>内定後バイトの予定を立てる。</li>
          </ul>
          <p>{`無事完遂。私の体力的に第一志望以外に複数社を受けることは難しかったので、せいぜいスカウトが来た企業
            (のうちただの宣伝ではなくちゃんと私のプロフィールを読んでいる企業)の面接を受けるくらいにして、
            インターンは第一志望だけ参加した。
            インターンで教わったことで印象的なのはテストの書き方。自分のコードが十分にモジュール化されていなくてテストに向いていないということが分かったので、
            Layered ArchitectureはじめinterfaceとDIによる抽象化に基づいたコードを学んで身につけるきっかけになった。
          `}</p>
        </div>
      </div>
      <h2 class="title">今に至る</h2>
    </div>
  
    <div class="box_container">
      <h2 class="title_future">(予定) 2026/04 フラー株式会社 入社(サーバーサイドエンジニア)</h2>
    </div>
  </div>
</MaxWidth>

<style>
  .box {
    display: flex;
  }
  .vertical_line {
    margin-left: 32px;
    margin-right: 8px;
    border-right: 1px solid var(--foreground);
  }
  .content {
    margin-left: 12px;
  }
  .title {
    color: var(--foreground3);
    margin: 0;
  }
  .title_future {
    color: var(--foreground2);
    margin: 0;
  }
</style>
