// src/routes/research/+page.svelte
<script>
import master_thesis from "$lib/assets/修士論文.pdf";
import MaxWidth from "../../components/maxWidth.svelte";
</script>

<MaxWidth>
  <h1>研究</h1>
  C*-環や(順序)Banach環や局所コンパクト群などに興味を持ち、
  和や積に関してスペクトルを保存するような写像がどれだけの情報を持っているか調べている(保存問題)。
  可換Banach環の場合、空間全体ではある程度分かっている(Hatori, Miura, and Takagi 2007)。
  私は修士の間、まずは具体的な空間として、ここで書くのが面倒になってきた。修士論文を読むと良い。
  <a href={master_thesis}>修士論文.pdf</a>
</MaxWidth>

// app/research/page.tsx
import MaxWidth from '../maxWidth';

export default function ResearchPage() {
  return (
    <MaxWidth>
      <h1>研究</h1>
      C*-環や(順序)Banach環や局所コンパクト群などに興味を持ち、
      和や積に関してスペクトルを保存するような写像がどれだけの情報を持っているか調べている(保存問題)。
      可換Banach環の場合、空間全体ではある程度分かっている(Hatori, Miura, and Takagi 2007)。
      私は修士の間、まずは具体的な空間として、ここで書くのが面倒になってきた。修士論文を読むと良い。
      <a href="/assets/修士論文.pdf">修士論文.pdf</a>
    </MaxWidth>
  );
}
